language: node_js
node_js:
  - "8"
cache: npm

git:
  depth: false

before_install:
  - echo "Installing dependencies.."

install:
  - npm install

script:
  - npm run build

after_success:
  - echo "Successfully built."